### ISSUE TITLE
Revalidation

### ISSUE THREAD

**Issue by sirupsen** [workos/authkit-nextjs#19]
Hey, thanks for providing a Next.js library, will change our app to use this instead of the hand-rolled one

I don't see any logic for revalidating the session occasionally in case the user is deleted, changed, or roles change? If a user is terminated, we'd need to reflect that at least within a few minutes, no?

**Comment by benoitgrelard** [comment]
By default, access tokens last 5min, so it will be refreshed by the middleware at worse in 5min (you can also configure this in the dashboard). You would receive any updates as part of that process. @cmatheson is there anything else we should/could do here?

**Comment by cmatheson** [comment]
Yeah that's right, the session gets refreshed when the access token is expired. Feel free to adjust the length of the access token expiry according to your requirements (could be 1m instead of 5m, for example). The updated access token will reflect changes in roles. If the user or organization membership have been deleted, the refresh will fail.

**Comment by sirupsen** [comment]
Did not know this! I'm not sure how I missed it!
